### ISSUE TITLE
Question about notes

### ISSUE THREAD

**Issue by ThierryRassat** [behearn/Hearn.Midi#2]
Hello,
Thank you for your program. It's very good for create midi file.
I have a question about notes : AS0, ASBF1, CSDF1, DSEF1, FSGF1, GSAF1
I see this tables conversion https://musicinformationretrieval.com/midi_conversion_table.html
Can you tell me the meaning of this notes ?
I search do make notes with freqency : 466.16Hz, 311.13Hz ?
Can you tell me if it's ok : 523.25Hz -> C5, 392Hz -> G4
Kind Regards,
Thierry

**Comment by behearn** [comment]
Hi,

Thanks for the feedback.

AS0 = A#0/Bb0 (Looks like I named it incorrectly.  It should be ASBF0 to be consistent!)
ASBF1 = A#1/Bb1
CSDF1 = C#1/Db1
etc

466.16Hz = A#4/Bb4 = ASBF4
311.13Hz = D#4/Eb4 = DSEF4

Yes, 523.25Hz = C5 & 392Hz = G4

(Assuming that conversion table is correct!)

Brian.

**Comment by ThierryRassat** [comment]
Thank you Brian for theses precisions.
Kind Regards,
Thierry
